'use server'

import { currentUser } from '@clerk/nextjs/server'
import { prisma } from '@/lib/prisma'
import { Prisma } from '@prisma/client'
import { generatePublicLinkToken } from '@/lib/tokens'
import { resend, EMAIL_CONFIG } from '@/lib/email/config'
import { handleServerActionError, requireAuth } from '@/lib/utils/server-actions'
import { invalidateDashboard, invalidateEntities } from '@/lib/cache'
import { extractBookingRequestFromFormData } from '@/lib/utils/form-data'
import { validateRequiredFields, isValidEmail, validateDateRange } from '@/lib/utils/validation'
import { parseDateInPanamaTime, parseEndDateInPanamaTime } from '@/lib/date/timezone'
import { buildCategoryKey, canonicalizeMainCategory } from '@/lib/category-utils'
import { getAppBaseUrl } from '@/lib/config/env'
import { logger } from '@/lib/logger'
import { generateRequestName, countBusinessRequests } from '@/lib/utils/request-naming'
import { extractDisplayName, extractUserEmail } from '@/lib/auth/user-display'
import { normalizeAdditionalRedemptionContacts } from '@/lib/booking-requests/additional-redemption-contacts'
import { buildPublicLinkPrefillSearchParams } from '@/lib/booking-requests/public-form-prefill'
import { renderPublicBookingRequestEmail } from '@/lib/email/templates/public-booking-request'

type AdditionalBankAccount = {
  bankAccountName: string
  bank: string
  accountNumber: string
  accountType: string
}

function normalizeAdditionalBankAccounts(value: unknown): AdditionalBankAccount[] {
  if (!Array.isArray(value)) return []

  return value
    .filter((item): item is Record<string, unknown> => !!item && typeof item === 'object' && !Array.isArray(item))
    .map((item) => ({
      bankAccountName: String(item.bankAccountName || '').trim(),
      bank: String(item.bank || '').trim(),
      accountNumber: String(item.accountNumber || '').trim(),
      accountType: String(item.accountType || '').trim(),
    }))
    .filter((item) => Object.values(item).some((fieldValue) => fieldValue.length > 0))
}

/**
 * Generate a public request link and send it via email
 * Supports sending to multiple email addresses
 */
export async function generateAndSendPublicLink(
  recipientEmails: string | string[],
  prefillQueryParams?: Record<string, string>
) {
  const authResult = await requireAuth()
  if (!('userId' in authResult)) {
    return authResult
  }

  const { userId } = authResult

  try {
    // Normalize to array and filter valid emails
    const emailArray = Array.isArray(recipientEmails) ? recipientEmails : [recipientEmails]
    const validEmails = emailArray
      .map(e => e?.toLowerCase().trim())
      .filter(e => e && e.includes('@'))
    
    // Remove duplicates
    const uniqueEmails = [...new Set(validEmails)]

    if (uniqueEmails.length === 0) {
      return { success: false, error: 'No se proporcionaron direcciones de correo electrónico válidas' }
    }

    // Get user information for email using centralized utility
    const user = await currentUser()
    const userEmail = extractUserEmail(user)
    const userName = extractDisplayName(user) || userEmail || 'Team Member'

    // Generate unique token
    const token = generatePublicLinkToken()

    // Create public link record (store first email as primary, all emails in a note)
    const primaryEmail = uniqueEmails[0]
    const publicLink = await prisma.publicRequestLink.create({
      data: {
        token,
        createdBy: userId,
        recipientEmail: primaryEmail,
      },
    })

    // Build public URL
    const baseUrl = getAppBaseUrl()
    const publicUrlSearchParams = buildPublicLinkPrefillSearchParams(uniqueEmails, prefillQueryParams)
    const publicUrl = publicUrlSearchParams.toString().length > 0
      ? `${baseUrl}/booking-request/${token}?${publicUrlSearchParams.toString()}`
      : `${baseUrl}/booking-request/${token}`

    // Send email with link to all recipients
    try {
      await resend.emails.send({
        from: `OfertaSimple <${EMAIL_CONFIG.from}>`,
        to: uniqueEmails, // All recipient emails
        cc: userEmail ? [userEmail] : [], // Copy to: logged-in user who created the link
        replyTo: userEmail || EMAIL_CONFIG.replyTo,
        subject: 'Complete su Solicitud de Booking - OS Deals',
        html: renderPublicBookingRequestEmail({
          recipientEmail: uniqueEmails.join(', '),
          publicUrl,
          senderName: userName,
        }),
      })

      logger.info(`Public link sent to ${uniqueEmails.join(', ')} (CC: ${userEmail || 'none'}) - generated by ${userId}`)
    } catch (emailError) {
      logger.error('Error sending public link email:', emailError)
      // Delete the link if email failed
      await prisma.publicRequestLink.delete({ where: { id: publicLink.id } })
      return {
        success: false,
        error: 'Error al enviar el correo electrónico. Por favor intente nuevamente.',
      }
    }

    return {
      success: true,
      data: {
        token: publicLink.token,
        url: publicUrl,
        recipientEmail: primaryEmail,
        recipientEmails: uniqueEmails,
        createdAt: publicLink.createdAt,
      },
    }
  } catch (error) {
    return handleServerActionError(error, 'generateAndSendPublicLink')
  }
}

/**
 * Validate a public request link token
 */
export async function validatePublicLinkToken(token: string) {
  try {
    const publicLink = await prisma.publicRequestLink.findUnique({
      where: { token },
    })

    if (!publicLink) {
      return { valid: false, error: 'Enlace inválido' }
    }

    if (publicLink.isUsed) {
      return { valid: false, error: 'Este enlace ya ha sido utilizado' }
    }

    return { valid: true, publicLink }
  } catch (error) {
    logger.error('Error validating public link token:', error)
    return { valid: false, error: 'Error al validar el enlace' }
  }
}

/**
 * Get public link by token
 */
export async function getPublicLinkByToken(token: string) {
  try {
    const publicLink = await prisma.publicRequestLink.findUnique({
      where: { token },
      include: {
        bookingRequest: true,
      },
    })

    return publicLink
  } catch (error) {
    logger.error('Error fetching public link:', error)
    return null
  }
}

/**
 * Submit a booking request from public form (no authentication required)
 * Sets status to 'approved' and links to the public link token
 */
export async function submitPublicBookingRequest(token: string, formData: FormData) {
  try {
    // Validate token first
    const validation = await validatePublicLinkToken(token)
    if (!validation.valid || !validation.publicLink) {
      return {
        success: false,
        error: validation.error || 'Enlace inválido o expirado',
      }
    }

    const publicLink = validation.publicLink

    // Extract all fields using utility
    const fields = extractBookingRequestFromFormData(formData)

    // Validate required fields
    const missing = validateRequiredFields(fields, ['name', 'businessEmail', 'startDate', 'endDate'])
    if (missing.length > 0) {
      return {
        success: false,
        error: `Campos requeridos faltantes: ${missing.join(', ')}`,
      }
    }

    // Validate email format
    if (!isValidEmail(fields.businessEmail!)) {
      return { success: false, error: 'Formato de correo electrónico inválido' }
    }

    // Parse dates in Panama timezone for consistency
    const startDateTime = parseDateInPanamaTime(fields.startDate!)
    const endDateTime = parseEndDateInPanamaTime(fields.endDate!)

    // Validate date range
    const dateValidation = validateDateRange(startDateTime, endDateTime)
    if (!dateValidation.valid) {
      return { success: false, error: dateValidation.error! }
    }

    // Build standardized category key
    const normalizedParentCategory = canonicalizeMainCategory(fields.parentCategory)
    const standardizedCategory = buildCategoryKey(
      normalizedParentCategory || null,
      fields.subCategory1 || null,
      fields.subCategory2 || null,
      fields.subCategory3 || null,
      null, // subCategory4
      fields.category
    )

    // Generate request name with format: "Business Name | Dec-15-2025 | #3"
    const existingCount = await countBusinessRequests(fields.name!)
    const requestName = generateRequestName(fields.name!, existingCount)

    const additionalEmailsJson: Prisma.InputJsonValue | typeof Prisma.JsonNull =
      fields.additionalEmails &&
      Array.isArray(fields.additionalEmails) &&
      fields.additionalEmails.length > 0
        ? (fields.additionalEmails.filter(
            (email: string) => email && email.trim() && email.includes('@')
          ) as Prisma.InputJsonValue)
        : Prisma.JsonNull

    // Convert JSON array fields to Prisma-compatible format (null -> Prisma.JsonNull)
    const redemptionMethodsJson: Prisma.InputJsonValue | typeof Prisma.JsonNull =
      fields.redemptionMethods && Array.isArray(fields.redemptionMethods) && fields.redemptionMethods.length > 0
        ? (fields.redemptionMethods as Prisma.InputJsonValue)
        : Prisma.JsonNull

    const pricingOptionsJson: Prisma.InputJsonValue | typeof Prisma.JsonNull =
      fields.pricingOptions && Array.isArray(fields.pricingOptions) && fields.pricingOptions.length > 0
        ? (fields.pricingOptions as Prisma.InputJsonValue)
        : Prisma.JsonNull

    const dealImagesJson: Prisma.InputJsonValue | typeof Prisma.JsonNull =
      fields.dealImages && Array.isArray(fields.dealImages) && fields.dealImages.length > 0
        ? (fields.dealImages as Prisma.InputJsonValue)
        : Prisma.JsonNull

    const additionalInfoJson: Prisma.InputJsonValue | typeof Prisma.JsonNull =
      fields.additionalInfo && typeof fields.additionalInfo === 'object'
        ? (fields.additionalInfo as Prisma.InputJsonValue)
        : Prisma.JsonNull

    const eventDaysJson: Prisma.InputJsonValue | typeof Prisma.JsonNull =
      fields.eventDays && Array.isArray(fields.eventDays) && fields.eventDays.length > 0
        ? (Array.from(
            new Set(
              fields.eventDays
                .filter((date): date is string => typeof date === 'string')
                .map((date) => date.trim())
                .filter((date) => date.length > 0)
            )
          ) as Prisma.InputJsonValue)
        : Prisma.JsonNull
    const normalizedAdditionalBankAccounts = normalizeAdditionalBankAccounts(fields.additionalBankAccounts)
    const additionalBankAccountsJson: Prisma.InputJsonValue | typeof Prisma.JsonNull =
      normalizedAdditionalBankAccounts.length > 0
        ? (normalizedAdditionalBankAccounts as Prisma.InputJsonValue)
        : Prisma.JsonNull
    const normalizedAdditionalRedemptionContacts = normalizeAdditionalRedemptionContacts(fields.additionalRedemptionContacts)
    const additionalRedemptionContactsJson: Prisma.InputJsonValue | typeof Prisma.JsonNull =
      normalizedAdditionalRedemptionContacts.length > 0
        ? (normalizedAdditionalRedemptionContacts as Prisma.InputJsonValue)
        : Prisma.JsonNull

    // Create booking request with status 'approved' (as requested)
    // Use the userId from the public link creator (createdBy)
    const bookingRequest = await prisma.bookingRequest.create({
      data: {
        name: requestName,
        category: standardizedCategory,
        parentCategory: normalizedParentCategory,
        subCategory1: fields.subCategory1,
        subCategory2: fields.subCategory2,
        subCategory3: fields.subCategory3,
        merchant: fields.merchant,
        businessEmail: fields.businessEmail!,
        additionalEmails: additionalEmailsJson,
        startDate: startDateTime,
        endDate: endDateTime,
        status: 'approved', // Public submissions are automatically approved
        sentAt: new Date(),
        approvedAt: new Date(),
        sourceType: 'public_link',
        publicLinkToken: token,
        userId: publicLink.createdBy, // Use the creator's userId
        processedAt: new Date(),
        // Configuración: Configuración General y Vigencia
        campaignDuration: fields.campaignDuration,
        campaignDurationUnit: fields.campaignDurationUnit || 'months',
        eventDays: eventDaysJson,
        isReplicatedRequest: fields.isReplicatedRequest,
        // Operatividad: Operatividad y Pagos
        redemptionMode: fields.redemptionMode,
        isRecurring: fields.isRecurring,
        recurringOfferLink: fields.recurringOfferLink,
        paymentType: fields.paymentType,
        paymentInstructions: fields.paymentInstructions,
        // Directorio: Directorio de Responsables
        redemptionContactName: fields.redemptionContactName,
        redemptionContactEmail: fields.redemptionContactEmail,
        redemptionContactPhone: fields.redemptionContactPhone,
        additionalRedemptionContacts: additionalRedemptionContactsJson,
        // Fiscales: Datos Fiscales, Bancarios y de Ubicación
        legalName: fields.legalName,
        rucDv: fields.rucDv,
        bankAccountName: fields.bankAccountName,
        bank: fields.bank,
        accountNumber: fields.accountNumber,
        accountType: fields.accountType,
        additionalBankAccounts: additionalBankAccountsJson,
        addressAndHours: fields.addressAndHours,
        provinceDistrictCorregimiento: fields.provinceDistrictCorregimiento,
        // Negocio: Reglas de Negocio y Restricciones
        includesTaxes: fields.includesTaxes,
        validOnHolidays: fields.validOnHolidays,
        hasExclusivity: fields.hasExclusivity,
        blackoutDates: fields.blackoutDates,
        exclusivityCondition: fields.exclusivityCondition,
        hasOtherBranches: fields.hasOtherBranches,
        // Descripción: Descripción y Canales de Venta
        redemptionMethods: redemptionMethodsJson,
        contactDetails: fields.contactDetails,
        socialMedia: fields.socialMedia,
        // Contenido: AI-Generated Content Fields
        nameEs: fields.nameEs,
        shortTitle: fields.shortTitle,
        emailTitle: fields.emailTitle,
        whatWeLike: fields.whatWeLike,
        aboutCompany: fields.aboutCompany,
        aboutOffer: fields.aboutOffer,
        goodToKnow: fields.goodToKnow,
        howToUseEs: fields.howToUseEs,
        // Estructura: Estructura de la Oferta
        offerMargin: fields.offerMargin,
        pricingOptions: pricingOptionsJson,
        dealImages: dealImagesJson,
        // Políticas: Políticas Generales
        cancellationPolicy: fields.cancellationPolicy,
        marketValidation: fields.marketValidation,
        additionalComments: fields.additionalComments,
        // Información Adicional (Dynamic template-based)
        additionalInfo: additionalInfoJson,
      },
    })

    // Create an approved event in the calendar (matching the approved booking request status)
    // This allows the event to be booked/rejected directly like internal requests
    const event = await prisma.event.create({
      data: {
        name: bookingRequest.name,
        description: null, // Events can have their own description if needed
        category: standardizedCategory,
        parentCategory: normalizedParentCategory,
        subCategory1: bookingRequest.subCategory1,
        subCategory2: bookingRequest.subCategory2,
        subCategory3: bookingRequest.subCategory3,
        business: bookingRequest.merchant,
        startDate: startDateTime,
        endDate: endDateTime,
        status: 'approved', // Create as approved to match booking request status and enable book/reject actions
        userId: publicLink.createdBy, // Use the creator's userId
        bookingRequestId: bookingRequest.id,
      },
    })

    // Link the event to the booking request
    await prisma.bookingRequest.update({
      where: { id: bookingRequest.id },
      data: { eventId: event.id },
    })

    // Log externally submitted approval milestone for audit/history reconstruction.
    try {
      await prisma.activityLog.create({
        data: {
          userId: 'external',
          userName: bookingRequest.businessEmail,
          userEmail: bookingRequest.businessEmail,
          action: 'APPROVE',
          entityType: 'BookingRequest',
          entityId: bookingRequest.id,
          entityName: bookingRequest.name,
          details: {
            statusChange: { from: 'public_submission', to: 'approved' },
            metadata: { source: 'public_request_link' },
          },
        },
      })
    } catch (logError) {
      logger.error('Error logging public request approval activity:', logError)
    }

    // Mark the public link as used
    await prisma.publicRequestLink.update({
      where: { id: publicLink.id },
      data: {
        isUsed: true,
        usedAt: new Date(),
      },
    })

    // Revalidate cache
    invalidateEntities(['booking-requests', 'public-request-links', 'events'])
    invalidateDashboard()

    return {
      success: true,
      data: {
        bookingRequestId: bookingRequest.id,
        requestName: bookingRequest.name,
      },
    }
  } catch (error) {
    logger.error('Error submitting public booking request:', error)
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Error al enviar la solicitud de booking',
    }
  }
}
