/**
 * Category type definitions
 */

// Recursive type for category hierarchy
// Can be an array of strings (leaf nodes) or nested objects
export type CategoryNode = string[] | { [key: string]: CategoryNode }

export type CategoryHierarchy = {
  [mainCategory: string]: CategoryNode
}

/**
 * CategoryOption - Used for UI dropdown display (flat hierarchy format)
 * Generated by getCategoryOptions() in lib/categories.ts
 */
export type CategoryOption = {
  label: string
  value: string
  parent: string
  sub1: string | null
  sub2: string | null
  sub3: string | null
  sub4: string | null
}

/**
 * CategoryRecord - Database category entity shape
 * Mirrors the fields from Prisma's Category model for form components
 * Use this when passing category data from DB to form components
 */
export type CategoryRecord = {
  id: string
  categoryKey: string
  parentCategory: string
  subCategory1: string | null
  subCategory2: string | null
  subCategory3: string | null
  subCategory4: string | null
}

export type CategoryColors = {
  bg: string
  text: string
  border: string
  indicator: string
}

export type CategoryDurations = {
  [category: string]: number
}

