import { useState, useRef } from 'react'
import AutoFixHighIcon from '@mui/icons-material/AutoFixHigh'
import type { BookingFormData } from '../types'
import { Input, Textarea, Button } from '@/components/ui'

interface DescripcionStepProps {
  formData: BookingFormData
  errors: Record<string, string>
  updateFormData: (field: keyof BookingFormData, value: any) => void
  isFieldRequired?: (fieldKey: string) => boolean
}

export default function DescripcionStep({ formData, errors, updateFormData, isFieldRequired = () => false }: DescripcionStepProps) {
  const [aiLoading, setAiLoading] = useState(false)
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false)
  const textareaRef = useRef<HTMLTextAreaElement>(null)

  // Auto-generate review when field is focused for the first time and is empty
  const handleFieldFocus = async () => {
    if (hasAutoGenerated || aiLoading || !formData.businessName?.trim()) return
    
    // Only auto-generate if field is empty
    if (!formData.businessReview?.trim()) {
      setHasAutoGenerated(true)
      await generateReviewFromBusinessName()
    }
  }

  const generateReviewFromBusinessName = async () => {
    if (!formData.businessName?.trim()) return
    
    setAiLoading(true)
    try {
      const response = await fetch('/api/ai/improve-business-review', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ 
          businessName: formData.businessName,
          searchInternet: true,
          addressAndHours: formData.addressAndHours,
        }),
      })
      if (!response.ok) throw new Error('No se pudo generar la reseña.')
      const data = await response.json()
      if (data?.text) {
        updateFormData('businessReview', data.text)
      }
    } catch (error) {
      console.error('AI generate review error', error)
    } finally {
      setAiLoading(false)
    }
  }

  const handleImproveWithAI = async () => {
    if (!formData.businessReview?.trim()) {
      // If empty, generate from business name
      await generateReviewFromBusinessName()
      return
    }
    
    // If has text, improve it
    setAiLoading(true)
    try {
      const response = await fetch('/api/ai/improve-business-review', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ 
          text: formData.businessReview,
          businessName: formData.businessName,
          addressAndHours: formData.addressAndHours,
        }),
      })
      if (!response.ok) throw new Error('No se pudo mejorar la reseña.')
      const data = await response.json()
      if (data?.text) {
        updateFormData('businessReview', data.text)
      }
    } catch (error) {
      console.error('AI improve error', error)
    } finally {
      setAiLoading(false)
    }
  }

  return (
    <div className="space-y-8">
      <div className="border-b border-gray-100 pb-4 mb-6">
        <h2 className="text-2xl font-bold text-gray-900">Descripción y Canales de Venta</h2>
        <p className="text-sm text-gray-500 mt-1">Información visible para el cliente.</p>
      </div>
      
      <div className="space-y-6">
        <div className="group">
          <label className="block text-sm font-semibold text-gray-700 mb-2">
            Número, correo electrónico y/o app específico
          </label>
          <Input
            value={formData.contactDetails}
            onChange={(e) => updateFormData('contactDetails', e.target.value)}
            placeholder="Detalles de contacto para canje"
          />
        </div>

        <div className="group">
          <label className="block text-sm font-semibold text-gray-700 mb-2">Redes Sociales y Web</label>
          <Input
            value={formData.socialMedia}
            onChange={(e) => updateFormData('socialMedia', e.target.value)}
            placeholder="Ej: @instagram_handle"
          />
        </div>

        <div className="group">
          <div className="flex items-center justify-between mb-2 gap-3">
            <label className="block text-sm font-semibold text-gray-700">Reseña del Negocio</label>
            <Button
              type="button"
              size="sm"
              variant="secondary"
              disabled={aiLoading || (!formData.businessReview?.trim() && !formData.businessName?.trim())}
              onClick={handleImproveWithAI}
              className="whitespace-nowrap bg-gradient-to-r from-purple-500 to-indigo-500 text-white hover:from-purple-600 hover:to-indigo-600 hover:text-white focus-visible:ring-purple-500 shadow-sm hover:shadow-md flex items-center gap-2"
            >
              <AutoFixHighIcon fontSize="small" />
              {aiLoading ? 'Generando...' : formData.businessReview?.trim() ? 'Mejorar con IA' : 'Generar con IA'}
            </Button>
          </div>
          <div className="space-y-2">
            {aiLoading && (
              <div className="flex items-center gap-2 text-sm text-purple-600 font-medium">
                <div className="w-4 h-4 border-2 border-purple-500 border-t-transparent rounded-full animate-spin"></div>
                <span>Buscando información en internet y generando reseña...</span>
              </div>
            )}
            <div className="relative">
              <Textarea
                ref={textareaRef}
                value={formData.businessReview}
                onChange={(e) => updateFormData('businessReview', e.target.value)}
                onFocus={handleFieldFocus}
                rows={6}
                maxLength={1000}
                placeholder={aiLoading ? 'Generando reseña con IA...' : 'Máximo 1,000 caracteres. Se generará automáticamente al enfocar el campo si está vacío.'}
                error={errors.businessReview}
                disabled={aiLoading}
                helperText={!aiLoading ? `${formData.businessReview.length}/1,000 caracteres` : undefined}
              />
            </div>
          </div>
        </div>

        <div className="group">
          <label className="block text-sm font-semibold text-gray-700 mb-2 flex items-center gap-2">
            <span>Detalle del Contenido (Temario/Sinopsis)</span>
            {isFieldRequired('offerDetails') ? (
              <span className="text-red-500">*</span>
            ) : (
              <span className="text-xs text-gray-400 font-normal">(Opcional)</span>
            )}
          </label>
          <Textarea
            value={formData.offerDetails}
            onChange={(e) => updateFormData('offerDetails', e.target.value)}
            rows={4}
            placeholder="Temario o Sinopsis/Descripción completa de la oferta..."
            error={errors.offerDetails}
          />
        </div>
      </div>
    </div>
  )
}

